# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# チュートリアル前章のアプリは RuboCop の対象外
AllCops:
  Exclude:
    - "environment/**/*"

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: true
Style/ClassMethods:
  Enabled: true

# シンボルの配列は %i / %I の %記法を強制（例: %i[index edit update]）
Style/SymbolArray:
  EnforcedStyle: percent
